# Generated by Django 2.2 on 2020-08-08 18:26

from django.conf import settings
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=25, unique=True)),
                ('active_from', models.DateField()),
                ('active_to', models.DateField()),
                ('discount', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('number', models.IntegerField(default=0)),
                ('valid', models.BooleanField(default=True)),
                ('user', models.ManyToManyField(related_name='coupons', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
