# Generated by Django 2.2 on 2020-08-09 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0003_coupon_max_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='max_discount',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=6),
        ),
    ]
