# Generated by Django 2.2 on 2020-08-05 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderss', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
